Adjust make-release to git.

diff --git a/admin/make-release b/admin/make-release
--- a/admin/make-release
+++ b/admin/make-release
@@ -3,25 +3,46 @@
 
 # Usage: make-release [branch]
 
+set -e
+
 repo=ukolovnik
-srcdir=`pwd`
 
 version=`sed -n "/version =/ s/.*= '\(.*\)'.*/\1/p" lib/version.php`
 
-tmp=`mktemp -dt $repo-build-XXXXXX`
+srcdir=`pwd`
 
+
+
+dotag=0
+if [ "x$1" = "xbranch" ] ; then
+    checkout=HEAD
+    dotag=1
+    # Pre release checks
+    if grep -q '^200[0-9]???? - ' ChangeLog ; then
+        echo 'ChangeLog does not seem to be finalised, aborting!'
+        exit 1
+    fi
+    shift
+elif [ "x$1" = "x" ] ; then
+    checkout=HEAD
+else 
+    checkout=$1
+    version=$1
+    shift
+fi
+
+tmp=`mktemp -dt $repo-build-XXXXXX`
 cd $tmp
 echo Working in $tmp
-if [ "x$1" = "xbranch" ] ; then
-    rel=RELEASE_`echo -n $version|tr . _`
-    svn cp -m "Tag release $version" svn+ssh://mort/home/svn/$repo/trunk svn+ssh://mort/home/svn/$repo/tags/$rel
-    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
-else
-    svn export svn+ssh://mort/home/svn/$repo/trunk $repo-$version
-fi
+echo "Creating release $version from $checkout"
+git clone -l $srcdir $repo-$version
 cd $repo-$version
+git checkout $checkout
+rm -rf .git
 ./admin/locales-generate
 cd ..
+
+echo 'Creating source tarballs...'
 tar cfz $repo-$version.tar.gz $repo-$version
 tar cfj $repo-$version.tar.bz2 $repo-$version
 7za a -bd -tzip $repo-$version.zip $repo-$version > /dev/null
@@ -30,3 +51,10 @@ tar cfj $repo-$version.tar.bz2 $repo-$version
 echo "Release is in $tmp directory:"
 ls -lh $tmp
 chmod 644 $repo-$version.*
+
+cd "$srcdir"
+
+if [ $dotag -eq 1 ] ; then
+    # Tag the release
+    git tag -m "Tag release $version" "$version"
+fi
